spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: msvc-catalogos
          uri: http://msvc-catalogos:8080
          predicates:
            - Path=/api/v1/rva/catalogos/**
          filters:
            - RemoveRequestHeader=Cookie
            - SaveSession
  security:
    oauth2:
      client:
        registration:
          spring:
            client-id: sec-pisa
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://${CONFIG_HOST:localhost}:8090/authorized
            scope: [openid, profile]
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://${CONFIG_HOST:localhost}:8101

eureka:
  client:
    service-url:
      defaultZone: http://${CONFIG_HOST:localhost}:8761/eureka