server:
  port: 8090
  tomcat:
    max-threads: 20
    accept-count: 50

spring:
  main:
    lazy-initialization: true
  cloud:
    gateway:
      server:
          routes:
            - id: msvc-usuarios
              uri: lb://msvc-usuarios
              predicates:
                - Path=/api/v1/rva/usuarios/**
              filters:
                - TokenRelay
                - name: CircuitBreaker
                  args:
                    name: msvc-usuarios
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession
            - id: msvc-catalogos
              uri: lb://msvc-catalogos
              predicates:
                - Path=/api/v1/rva/catalogos/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-catalogos
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession
                - TokenRelay
            - id: msvc-reclutamiento-alta-cita
              uri: lb://msvc-reclutamiento-alta-cita
              predicates:
                - Path=/api/v1/rva/alta-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-alta-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - TokenRelay
            - id: msvc-reclutamiento-consulta-cita
              uri: lb://msvc-reclutamiento-consulta-cita
              predicates:
                - Path=/api/v1/rva/consulta-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-consulta-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - TokenRelay
            - id: msvc-reclutamiento-reagenda-cita
              uri: lb://msvc-reclutamiento-reagenda-cita
              predicates:
                - Path=/api/v1/rva/reagenda-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-reagenda-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - TokenRelay
            - id: msvc-cipher
              uri: lb://msvc-cipher
              predicates:
                - Path=/api/v1/rva/cipher/**
              filters:
                - TokenRelay
            - id: msvc-auth
              uri: lb://msvc-auth
              predicates:
                - Path=/api/v1/rva/auth/**
              filters:
                - StripPrefix=4
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://msvc-auth:8101

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  metrics:
    export:
      simple:
        enabled: false
  tracing:
    enabled: false

logging:
  level:
    root: INFO

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      msvc-catalogos:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
      msvc-catalogos:
        base-config: defecto

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/