server:
  address: 0.0.0.0
  tomcat:
    max-threads: 20
    accept-count: 50

spring:
  main:
    lazy-initialization: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      server:
        webflux:
          routes:
            - id: msvc-catalogos
              uri: lb://msvc-catalogos
              predicates:
                - Path=/api/v1/rva/catalogos/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-catalogos
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession

            - id: msvc-reclutamiento-alta-cita
              uri: lb://msvc-reclutamiento-alta-cita
              predicates:
                - Path=/api/v1/rva/alta-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-alta-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession

            - id: msvc-reclutamiento-consulta-cita
              uri: lb://msvc-reclutamiento-consulta-cita
              predicates:
                - Path=/api/v1/rva/consulta-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-consulta-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession

            - id: msvc-reclutamiento-reagenda-cita
              uri: lb://msvc-reclutamiento-reagenda-cita
              predicates:
                - Path=/api/v1/rva/reagenda-cita/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-reclutamiento-reagenda-cita
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession      -

            - id: msvc-cipher
              uri: lb://msvc-cipher
              predicates:
                - Path=/api/v1/rva/cipher/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-cipher
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - RemoveRequestHeader=Cookie
                - SaveSession
            - id: msvc-auth
              uri: lb://msvc-auth
              predicates:
                - Path=/api/v1/rva/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: msvc-auth
                    statusCodes:
                      - 500
                      - 404
                      - 403
                      - 401
                      - 400
                - StripPrefix=4
                - RemoveRequestHeader=Cookie
                - SaveSession
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  metrics:
    export:
      simple:
        enabled: false
  tracing:
    enabled: false

logging:
  level:
    root: INFO

# Configuración de Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      msvc-catalogos:
        base-config: defecto
      msvc-reclutamiento-alta-cita:
        base-config: defecto
      msvc-reclutamiento-consulta-cita:
        base-config: defecto
      msvc-reclutamiento-reagenda-cita:
        base-config: defecto
      msvc-cipher:
        base-config: defecto
      msvc-auth:
        base-config: defecto

  # Configuración de Resilience4j Time Limiter
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
      msvc-catalogos:
        base-config: defecto
      msvc-reclutamiento-alta-cita:
        base-config: defecto
      msvc-reclutamiento-consulta-cita:
        base-config: defecto
      msvc-cipher:
        base-config: defecto
      msvc-auth:
        base-config: defecto